In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("C:\\Users\\pooja\\OneDrive\\Desktop\\Data analyst(Pooja)\\pooja_portfolio_2026\\SMM_3_ABtesting_marketting\\marketing_campaign_data_v2.csv")

df.head()

,date,platform,age_group,region,device,campaign_type,hour,impressions,month,click_rate,clicks,cpc,cost,conversion_rate,conversions,day,fatigue_factor
0,2025-01-01,Google,36-50,North India,Desktop,Text,8,79015,1,0.019919,1573,0.9,1415.7,0.093552,147,0,1.00000
1,2025-01-02,Instagram,36-50,West India,Desktop,Video,7,90463,1,0.042704,3863,1.3,5021.9,0.140506,541,1,0.99996
2,2025-01-03,Instagram,36-50,South India,Desktop,Image,9,34292,1,0.041122,1410,1.3,1833.0,0.190822,268,2,0.99992
3,2025-01-04,Instagram,26-35,North India,Mobile,Image,8,20491,1,0.036983,757,1.3,984.1,0.154757,116,3,0.99988
4,2025-01-05,Google,36-50,North India,Mobile,Video,7,58294,1,0.076980,4487,0.9,4038.3,0.149306,668,4,0.99984

In [8]:
df.shape

(5000, 17)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             5000 non-null   object
 1   platform         5000 non-null   object
 2   age_group        5000 non-null   object
 3   region           5000 non-null   object
 4   device           5000 non-null   object
 5   campaign_type    5000 non-null   object
 6   hour             5000 non-null   int64
 7   impressions      5000 non-null   int64
 8   month            5000 non-null   int64
 9   click_rate       5000 non-null   float64
 10  clicks           5000 non-null   int64
 11  cpc              5000 non-null   float64
 12  cost             5000 non-null   float64
 13  conversion_rate  5000 non-null   float64
 14  conversions      5000 non-null   int64
 15  day              5000 non-null   int64
 16  fatigue_factor   5000 non-null   float64
dtypes: float64(5), int64(6), object(6)
memory usage: 664.2+ KB

In [12]:
df.isnull().sum()

date               0
platform           0
age_group          0
region             0
device             0
campaign_type      0
hour               0
impressions        0
month              0
click_rate         0
clicks             0
cpc                0
cost               0
conversion_rate    0
conversions        0
day                0
fatigue_factor     0
dtype: int64

In [14]:
df.describe()

,hour,impressions,month,click_rate,clicks,cpc,cost,conversion_rate,conversions,day,fatigue_factor
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,11.635400,50754.585000,6.430600,0.059494,3020.290800,1.080160,3365.990680,0.115882,314.035400,2499.500000,0.900020
std,6.908344,28742.727724,3.427584,0.023311,2174.972389,0.199033,2719.433518,0.047368,278.171188,1443.520003,0.057741
min,0.000000,1010.000000,1.000000,0.017896,32.000000,0.900000,28.800000,0.032542,1.000000,0.000000,0.800040
25%,6.000000,25350.250000,3.000000,0.040956,1294.000000,0.900000,1322.450000,0.076816,110.000000,1249.750000,0.850030
50%,12.000000,51489.500000,6.000000,0.057277,2634.500000,0.900000,2726.100000,0.112173,241.000000,2499.500000,0.900020
75%,18.000000,75506.250000,9.000000,0.073880,4270.750000,1.300000,4659.200000,0.149094,435.000000,3749.250000,0.950010
max,23.000000,99989.000000,12.000000,0.154092,12891.000000,1.300000,16758.300000,0.281961,2107.000000,4999.000000,1.000000

In [16]:
df["ctr"] = df["clicks"] / df["impressions"]

df[["clicks", "impressions", "ctr"]].head()

   clicks  impressions       ctr
0    1573        79015  0.019908
1    3863        90463  0.042703
2    1410        34292  0.041117
3     757        20491  0.036943
4    4487        58294  0.076972

In [18]:
df["conversion_rate_actual"] = (
    df["conversions"] / df["clicks"]
)

df[["clicks", "conversions", "conversion_rate_actual"]].head()

   clicks  conversions  conversion_rate_actual
0    1573          147                0.093452
1    3863          541                0.140047
2    1410          268                0.190071
3     757          116                0.153236
4    4487          668                0.148875

In [20]:
df["conversion_rate_actual"] = (
    df["conversions"] / df["clicks"]
)

df[["clicks", "conversions", "conversion_rate_actual"]].head()

   clicks  conversions  conversion_rate_actual
0    1573          147                0.093452
1    3863          541                0.140047
2    1410          268                0.190071
3     757          116                0.153236
4    4487          668                0.148875

In [22]:
df["cpc_actual"] = df["cost"] / df["clicks"]

df[["cost", "clicks", "cpc_actual"]].head()

     cost  clicks  cpc_actual
0  1415.7    1573         0.9
1  5021.9    3863         1.3
2  1833.0    1410         1.3
3   984.1     757         1.3
4  4038.3    4487         0.9

In [24]:
df["cost_per_conversion"] = (
    df["cost"] / df["conversions"]
)

df[["cost", "conversions", "cost_per_conversion"]].head()

     cost  conversions  cost_per_conversion
0  1415.7          147             9.630612
1  5021.9          541             9.282625
2  1833.0          268             6.839552
3   984.1          116             8.483621
4  4038.3          668             6.045359

In [26]:
platform_summary = df.groupby("platform").agg({
    "impressions": "mean",
    "clicks": "mean",
    "cost": "mean",
    "conversions": "mean",
    "ctr": "mean",
    "conversion_rate_actual": "mean",
    "cost_per_conversion": "mean"
})

platform_summary

,impressions,clicks,cost,conversions,ctr,conversion_rate_actual,cost_per_conversion
platform,,,,,,,
Google,50629.942868,2549.069141,2294.162227,266.880277,0.050265,0.103079,10.725517
Instagram,50906.679396,3595.298401,4673.887922,371.576377,0.070703,0.103716,15.285113

In [28]:
region_summary = df.groupby("region").agg({
    "conversions": "mean",
    "cost_per_conversion": "mean",
    "ctr": "mean"
})

region_summary

             conversions  cost_per_conversion       ctr
region
North India   294.484902            13.417011  0.059898
South India   335.012720            11.748657  0.059243
West India    313.063855            13.155078  0.059261

In [30]:
df["date"] = pd.to_datetime(df["date"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    5000 non-null   datetime64[ns]
 1   platform                5000 non-null   object
 2   age_group               5000 non-null   object
 3   region                  5000 non-null   object
 4   device                  5000 non-null   object
 5   campaign_type           5000 non-null   object
 6   hour                    5000 non-null   int64
 7   impressions             5000 non-null   int64
 8   month                   5000 non-null   int64
 9   click_rate              5000 non-null   float64
 10  clicks                  5000 non-null   int64
 11  cpc                     5000 non-null   float64
 12  cost                    5000 non-null   float64
 13  conversion_rate         5000 non-null   float64
 14  conversions             5000 non-null   int64
 15  day                     5000 non-null   int64
 16  fatigue_factor          5000 non-null   float64
 17  ctr                     5000 non-null   float64
 18  conversion_rate_actual  5000 non-null   float64
 19  cpc_actual              5000 non-null   float64
 20  cost_per_conversion     5000 non-null   float64
dtypes: datetime64[ns](1), float64(9), int64(6), object(5)
memory usage: 820.4+ KB

In [32]:
df["month"] = df["date"].dt.month

monthly_conversions = df.groupby("month")["conversions"].sum()

monthly_conversions

month
1     138936
2     122146
3     151159
4     182373
5     120364
6     114803
7     134584
8     134316
9     119431
10    116281
11    118961
12    116823
Name: conversions, dtype: int64

In [42]:
df.to_csv("C:\\Users\\pooja\\OneDrive\\Desktop\\Data analyst(Pooja)\\pooja_portfolio_2026\\SMM_3_ABtesting_marketting\\cleaned_marketing_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [38]:
# Marketing Campaign Data Cleaning
## KPI Feature Engineering
## Platform Performance Analysis