In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [5]:
df = pd.read_csv("C:\\Users\\pooja\\OneDrive\\Desktop\\Data analyst(Pooja)\\pooja_portfolio_2026\\SMM_3_ABtesting_marketting\\cleaned_marketing_data.csv")

df.head()

,date,platform,age_group,region,device,campaign_type,hour,impressions,month,click_rate,...,cpc,cost,conversion_rate,conversions,day,fatigue_factor,ctr,conversion_rate_actual,cpc_actual,cost_per_conversion
0,2025-01-01,Google,36-50,North India,Desktop,Text,8,79015,1,0.019919,...,0.9,1415.7,0.093552,147,0,1.00000,0.019908,0.093452,0.9,9.630612
1,2025-01-02,Instagram,36-50,West India,Desktop,Video,7,90463,1,0.042704,...,1.3,5021.9,0.140506,541,1,0.99996,0.042703,0.140047,1.3,9.282625
2,2025-01-03,Instagram,36-50,South India,Desktop,Image,9,34292,1,0.041122,...,1.3,1833.0,0.190822,268,2,0.99992,0.041117,0.190071,1.3,6.839552
3,2025-01-04,Instagram,26-35,North India,Mobile,Image,8,20491,1,0.036983,...,1.3,984.1,0.154757,116,3,0.99988,0.036943,0.153236,1.3,8.483621
4,2025-01-05,Google,36-50,North India,Mobile,Video,7,58294,1,0.076980,...,0.9,4038.3,0.149306,668,4,0.99984,0.076972,0.148875,0.9,6.045359

In [7]:
df["ctr"] = df["clicks"] / df["impressions"]

df.head()

,date,platform,age_group,region,device,campaign_type,hour,impressions,month,click_rate,...,cpc,cost,conversion_rate,conversions,day,fatigue_factor,ctr,conversion_rate_actual,cpc_actual,cost_per_conversion
0,2025-01-01,Google,36-50,North India,Desktop,Text,8,79015,1,0.019919,...,0.9,1415.7,0.093552,147,0,1.00000,0.019908,0.093452,0.9,9.630612
1,2025-01-02,Instagram,36-50,West India,Desktop,Video,7,90463,1,0.042704,...,1.3,5021.9,0.140506,541,1,0.99996,0.042703,0.140047,1.3,9.282625
2,2025-01-03,Instagram,36-50,South India,Desktop,Image,9,34292,1,0.041122,...,1.3,1833.0,0.190822,268,2,0.99992,0.041117,0.190071,1.3,6.839552
3,2025-01-04,Instagram,26-35,North India,Mobile,Image,8,20491,1,0.036983,...,1.3,984.1,0.154757,116,3,0.99988,0.036943,0.153236,1.3,8.483621
4,2025-01-05,Google,36-50,North India,Mobile,Video,7,58294,1,0.076980,...,0.9,4038.3,0.149306,668,4,0.99984,0.076972,0.148875,0.9,6.045359

In [9]:
df_encoded = pd.get_dummies(
    df,
    columns=["platform", "campaign_type", "device", "region"],
    drop_first=True
)

df_encoded.head()

,date,age_group,hour,impressions,month,click_rate,clicks,cpc,cost,conversion_rate,...,ctr,conversion_rate_actual,cpc_actual,cost_per_conversion,platform_Instagram,campaign_type_Text,campaign_type_Video,device_Mobile,region_South India,region_West India
0,2025-01-01,36-50,8,79015,1,0.019919,1573,0.9,1415.7,0.093552,...,0.019908,0.093452,0.9,9.630612,False,True,False,False,False,False
1,2025-01-02,36-50,7,90463,1,0.042704,3863,1.3,5021.9,0.140506,...,0.042703,0.140047,1.3,9.282625,True,False,True,False,False,True
2,2025-01-03,36-50,9,34292,1,0.041122,1410,1.3,1833.0,0.190822,...,0.041117,0.190071,1.3,6.839552,True,False,False,False,True,False
3,2025-01-04,26-35,8,20491,1,0.036983,757,1.3,984.1,0.154757,...,0.036943,0.153236,1.3,8.483621,True,False,False,True,False,False
4,2025-01-05,36-50,7,58294,1,0.076980,4487,0.9,4038.3,0.149306,...,0.076972,0.148875,0.9,6.045359,False,False,True,True,False,False

In [11]:
X = df_encoded[[
    "impressions",
    "clicks",
    "cost",
    "ctr",
    "hour",
    "platform_Instagram",
    "campaign_type_Text",
    "campaign_type_Video",
    "device_Mobile",
    "region_South India",
    "region_West India"
]]

y = df_encoded["conversions"]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (4000, 11)
Testing Shape: (1000, 11)

In [15]:
model = LinearRegression()

model.fit(X_train, y_train)

print("✅ Model trained successfully!")

✅ Model trained successfully!

In [17]:
y_pred = model.predict(X_test)

print(y_pred[:5])

[104.17573613 146.53620119 136.20394213 146.25868157 236.37320748]

In [19]:
mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 104.53893877513916

In [21]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("RMSE:", rmse)

RMSE: 147.58408417340726

In [23]:
r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)

R2 Score: 0.7111632274553991

In [25]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

importance.sort_values(by="Coefficient", ascending=False)

                Feature  Coefficient
3                   ctr    81.615381
7   campaign_type_Video    58.284480
9    region_South India    43.638011
10    region_West India    10.730556
1                clicks     0.100616
2                  cost     0.003712
0           impressions    -0.000072
4                  hour    -0.261338
8         device_Mobile    -3.598228
5    platform_Instagram    -8.566247
6    campaign_type_Text   -49.638045

In [ ]:
# Business Insights

- Click volume is the strongest predictor of conversions.
- Video campaigns outperform text campaigns.
- Mobile users show higher engagement.
- Google Ads generate more stable conversion behavior.

In [27]:
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

results.to_csv("../regression_predictions.csv", index=False)

print("✅ Predictions saved successfully!")

✅ Predictions saved successfully!